import html2pdf from 'html2pdf.js';

export interface PDFExportOptions {
  includeHeader?: boolean;
  includeFooter?: boolean;
  companyName?: string;
  darkMode?: boolean;
};

/**
 * Enhanced service for exporting SOP content to PDF with improved formatting
 */
export class EnhancedPDFExport {
  /**
   * Export HTML element to PDF with enhanced styling
   */
  static async exportToPDF(
    elementId: string,
    fileName: string,
    options: PDFExportOptions = {}
  ) {
    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error(`Element with ID '${elementId}' not found`);
      }
      
      // Default options
      const {
        includeHeader = true,
        includeFooter = true,
        companyName = 'SOP Builder',
        darkMode = false
      } = options;
      
      // Apply temporary styles for PDF export
      const originalStyles = element.getAttribute('style') || '';
      element.style.padding = '30px';
      element.style.backgroundColor = '#ffffff';
      element.style.color = '#333333';
      element.style.fontFamily = 'Arial, sans-serif';
      element.style.lineHeight = '1.5';
      
      // Enhance step styling
      const stepElements = element.querySelectorAll('.flex-shrink-0');
      stepElements.forEach(stepElement => {
        if (stepElement instanceof HTMLElement) {
          stepElement.style.backgroundColor = '#4f46e5';
          stepElement.style.color = '#ffffff';
          stepElement.style.boxShadow = '0 2px 4px rgba(0,0,0,0.1)';
        }
      });
      
      // Enhance step text
      const stepTextElements = element.querySelectorAll('.flex-1 p');
      stepTextElements.forEach(textElement => {
        if (textElement instanceof HTMLElement) {
          textElement.style.fontSize = '14px';
          textElement.style.color = '#333333';
        }
      });
      
      // Add header if requested
      let headerElement = null;
      if (includeHeader) {
        headerElement = document.createElement('div');
        headerElement.style.textAlign = 'center';
        headerElement.style.marginBottom = '30px';
        headerElement.style.borderBottom = '2px solid #4f46e5';
        headerElement.style.paddingBottom = '15px';
        
        const logoText = document.createElement('h2');
        logoText.textContent = companyName;
        logoText.style.margin = '0';
        logoText.style.color = '#4f46e5';
        logoText.style.fontSize = '24px';
        logoText.style.fontWeight = 'bold';
        
        const dateText = document.createElement('div');
        dateText.textContent = new Date().toLocaleDateString('en-US', {
          weekday: 'long',
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        });
        dateText.style.fontSize = '12px';
        dateText.style.color = '#666666';
        dateText.style.marginTop = '8px';
        
        headerElement.appendChild(logoText);
        headerElement.appendChild(dateText);
        element.prepend(headerElement);
      }
      
      // Add footer if requested
      let footerElement = null;
      if (includeFooter) {
        footerElement = document.createElement('div');
        footerElement.style.textAlign = 'center';
        footerElement.style.marginTop = '30px';
        footerElement.style.borderTop = '1px solid #dddddd';
        footerElement.style.paddingTop = '15px';
        footerElement.style.fontSize = '10px';
        footerElement.style.color = '#666666';
        
        const footerText = document.createElement('p');
        footerText.textContent = `Generated by ${companyName} on ${new Date().toLocaleDateString()}`;
        footerText.style.margin = '0';
        
        const pageNumbers = document.createElement('p');
        pageNumbers.textContent = 'Page 1';
        pageNumbers.style.margin = '5px 0 0 0';
        pageNumbers.style.fontSize = '9px';
        pageNumbers.style.fontStyle = 'italic';
        
        footerElement.appendChild(footerText);
        footerElement.appendChild(pageNumbers);
        element.appendChild(footerElement);
      }
      
      // Enhance materials section if present
      const materialsList = element.querySelector('.list-disc');
      if (materialsList instanceof HTMLElement) {
        materialsList.style.backgroundColor = '#f9f9f9';
        materialsList.style.padding = '15px 15px 15px 35px';
        materialsList.style.borderRadius = '6px';
        materialsList.style.border = '1px solid #e5e7eb';
      }
      
      // Enhance headings
      const headings = element.querySelectorAll('h1, h2, h3');
      headings.forEach(heading => {
        if (heading instanceof HTMLElement) {
          heading.style.color = '#4f46e5';
          heading.style.marginBottom = '15px';
          heading.style.fontWeight = 'bold';
        }
      });
      
      // Configure PDF options with better quality and formatting
      const pdfOptions: Html2PdfOptions = {
        margin: [20, 20] as [number, number],
        filename: `${fileName}.pdf`,
        image: { type: 'jpeg', quality: 0.99 },
        html2canvas: { 
          scale: 2, 
          useCORS: true, 
          logging: false,
          letterRendering: true
        },
        jsPDF: { 
          unit: 'mm', 
          format: 'a4', 
          orientation: 'portrait',
          compress: true,
          precision: 16
        }
      };
      
      // Generate PDF
      await html2pdf().from(element).set(pdfOptions).save();
      
      // Clean up - remove added elements and restore original styles
      if (headerElement) {
        element.removeChild(headerElement);
      }
      
      if (footerElement) {
        element.removeChild(footerElement);
      }
      
      element.setAttribute('style', originalStyles);
    } catch (error) {
      console.error("Enhanced PDF export failed:", error);
      throw error;
    }
  }
}